language: perl
os:
  - linux
  - osx
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
matrix:
  allow_failures:
    - os: osx
install:
  - provision/run.sh
notifications:
  email: false
sudo: required
